# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
development:
  <<: *default
  database: db/development.sqlite3
test:
  <<: *default
  database: db/test.sqlite3
production:
  <<: *default
  database: db/production.sqlite3
  
  
# development:
#   adapter:  postgresql
#   host:     localhost
#   encoding: utf8
#   database: gopurpose_development
#   pool:     5
#   username: <%= ENV['rubyuser'] %>
#   password: 
#   template: template0
#   # others options

# test:
#   adapter:  postgresql
#   host:     127.0.0.1
#   encoding: utf8
#   database: gopurpose_test
#   pool:     5
#   username: <%= ENV['rubyuser'] %>
#   password: 
#   template: template0
#   # others options

# production:
#   adapter:  postgresql
#   host:     127.0.0.1
#   encoding: utf8
#   database: gopurpose_production
#   pool:     5
#   username: <%= ENV['rubyuser'] %>
#   password: 
#   template: template0